### PR TITLE
[CICD-43] Add circle ci build number support

### PR DESCRIPTION
**Pull request by DanielCMS**
With this changes we can add circle ci build number to the built file

### CODE REVIEW

**Comment by DanielCMS** [comment]
I will merge this for now for testing purpose

**Review by archit — COMMENTED** [review]
why didn't you call this module `version-commit-circleci`? :thinking: 

Using `-circle`, seems to generic.

Also, have you considered sending these updates upstream? I'm sure the community could use this.

**Comment by DanielCMS** [comment]
@archit Sure let me do `version-commit-circleci`.

And for the upstream one, let me do that when we got extra time.... Right now the code is not in the best form it should be, even though it does the job

**Comment by archit** [comment]
The code looks fine. I compared it to `version-commit`, and there is only a diff of 3 lines. I think the upstream folks will consider it. Its very easy to make a PR for upstream via GitHub, just start a new PR, but point the original branch to point to the original fork, not this repo's master.

**Comment by DanielCMS** [comment]
The thing is that right now they want the revision data to be depending on the source files only (based on their README), so a circle CI build number should not be added. But let me try anyway to see how they feel

**Pull request merged**
